name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /home/code/sfind
            git fetch origin
            git checkout main
            git pull
            docker build -t sfind-v1 .
            docker stop sfind-v1-container  true
            docker rm sfind-v1-container  true
            docker run -d --name sfind-v1-container -p 3100:3100 sfind-v1
